"""Adaptive Threat Scoring Engine - Self-learning algorithm for fintech security assessment.

This engine implements a lightweight online-learning system that:
1. Builds statistical models from scan observations (no external training data needed)
2. Detects anomalies by comparing current scans against learned baselines
3. Dynamically adjusts threat severity weights based on observed threat co-occurrence patterns
4. Generates AI-powered insights by identifying correlations between security indicators
5. Maintains a decay-weighted memory of past observations for continuous adaptation

The algorithm uses:
- Exponential Moving Averages (EMA) for baseline metrics
- Bayesian-inspired confidence scoring for pattern detection
- Co-occurrence matrices for threat correlation discovery
- Entropy-based anomaly detection for identifying unusual security postures
"""

import math
import hashlib
import json
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any


@dataclass
class AdaptiveInsight:
    """An insight generated by the adaptive learning engine."""
    type: str       # "trend", "anomaly", "recommendation", "learning"
    title: str
    description: str
    confidence: float   # 0.0 to 1.0
    impact: str         # "high", "medium", "low"


@dataclass
class SecurityProfile:
    """Statistical profile of observed security characteristics."""
    header_coverage_mean: float = 0.5
    header_coverage_var: float = 0.1
    threat_count_mean: float = 5.0
    threat_count_var: float = 10.0
    ssl_strength_mean: float = 0.8
    ssl_strength_var: float = 0.05
    compliance_rate_mean: float = 0.6
    compliance_rate_var: float = 0.1
    observation_count: int = 0
    severity_distribution: dict = field(default_factory=lambda: {
        "CRITICAL": 0.05, "HIGH": 0.15, "MEDIUM": 0.35, "LOW": 0.35, "INFO": 0.10
    })
    # Co-occurrence matrix: tracks how often threat categories appear together
    category_cooccurrence: dict = field(default_factory=dict)
    # Learned threat weight adjustments
    threat_weight_adjustments: dict = field(default_factory=dict)
    last_updated: str = ""


class AdaptiveEngine:
    """Self-learning engine that adapts threat scoring based on observed patterns.

    The engine learns through three mechanisms:

    1. **Baseline Learning**: Maintains exponential moving averages of security
       metrics (header coverage, SSL strength, threat counts, compliance rates).
       New observations update the baseline with a configurable learning rate.

    2. **Correlation Discovery**: Builds a co-occurrence matrix of threat
       categories. When certain threat types consistently appear together,
       the engine learns to flag this as a correlated attack surface.

    3. **Anomaly Detection**: Uses z-score analysis against the learned
       baseline to identify scans that deviate significantly from the norm,
       flagging both unusually good and unusually poor security postures.
    """

    LEARNING_RATE = 0.15          # EMA alpha for updating baselines
    ANOMALY_THRESHOLD = 1.8       # Z-score threshold for anomaly detection
    MIN_OBSERVATIONS = 3          # Minimum observations before generating trend insights
    DECAY_FACTOR = 0.95           # Memory decay per observation
    SEVERITY_WEIGHTS = {
        "CRITICAL": 25, "HIGH": 15, "MEDIUM": 8, "LOW": 3, "INFO": 1
    }

    def __init__(self, profile_path: str | None = None):
        self.profile_path = profile_path or self._default_profile_path()
        self.profile = self._load_profile()

    def analyze(
        self,
        scan_results: dict,
        content_results: dict,
        threats: list,
        compliance_issues: list,
        security_score: dict,
        compliance_score: dict,
    ) -> list[AdaptiveInsight]:
        """Analyze scan results and generate adaptive insights.

        This is the main entry point. It:
        1. Extracts features from the scan
        2. Compares against learned baselines
        3. Updates the model with new observations
        4. Generates insights based on detected patterns
        """
        features = self._extract_features(
            scan_results, content_results, threats, compliance_issues,
            security_score, compliance_score,
        )

        insights = []

        # Phase 1: Anomaly detection against learned baselines
        insights.extend(self._detect_anomalies(features))

        # Phase 2: Threat correlation analysis
        insights.extend(self._analyze_correlations(threats))

        # Phase 3: Compliance pattern analysis
        insights.extend(self._analyze_compliance_patterns(compliance_issues, compliance_score))

        # Phase 4: Security posture assessment with adaptive thresholds
        insights.extend(self._assess_posture(features, threats))

        # Phase 5: Generate learned recommendations
        insights.extend(self._generate_recommendations(features, threats, compliance_issues))

        # Phase 6: Update the model with this observation (learning step)
        self._update_model(features, threats)

        # Sort by confidence * impact weight
        impact_weights = {"high": 3, "medium": 2, "low": 1}
        insights.sort(
            key=lambda i: i.confidence * impact_weights.get(i.impact, 1),
            reverse=True,
        )

        # Keep top insights
        return insights[:8]

    def adjust_scores(
        self,
        security_score: dict,
        compliance_score: dict,
        threats: list,
    ) -> dict:
        """Adjust scores based on learned threat weight patterns.

        If the engine has learned that certain threat combinations are
        more dangerous than their individual scores suggest, it applies
        a correction factor.
        """
        adjusted_security = dict(security_score)
        adjusted_compliance = dict(compliance_score)

        if self.profile.observation_count < self.MIN_OBSERVATIONS:
            return {
                "security_score": adjusted_security,
                "compliance_score": adjusted_compliance,
            }

        # Calculate correlation penalty
        categories = [t.category if hasattr(t, 'category') else t.get('category', '') for t in threats]
        unique_cats = set(categories)

        correlation_penalty = 0
        for cat1 in unique_cats:
            for cat2 in unique_cats:
                if cat1 >= cat2:
                    continue
                pair_key = f"{min(cat1, cat2)}||{max(cat1, cat2)}"
                cooccurrence = self.profile.category_cooccurrence.get(pair_key, 0)
                if cooccurrence > 3:
                    # Strong correlation detected - these threats reinforce each other
                    correlation_penalty += min(2, cooccurrence * 0.3)

        if correlation_penalty > 0:
            penalty = min(10, int(correlation_penalty))
            adjusted_security["score"] = max(0, adjusted_security.get("score", 0) - penalty)
            # Update rating based on new score
            adjusted_security["rating"] = self._score_to_rating(adjusted_security["score"])

        return {
            "security_score": adjusted_security,
            "compliance_score": adjusted_compliance,
        }

    def _extract_features(
        self, scan_results, content_results, threats, compliance_issues,
        security_score, compliance_score,
    ) -> dict:
        """Extract numerical features from scan results for learning."""
        headers = scan_results.get("headers", {})
        present = len(headers.get("present", {}))
        missing = len(headers.get("missing", []))
        total_headers = present + missing

        ssl = scan_results.get("ssl", {})
        ssl_score = 1.0 if ssl.get("has_ssl") else 0.0
        protocol = ssl.get("protocol_version", "")
        if protocol == "TLSv1.3":
            ssl_score = 1.0
        elif protocol == "TLSv1.2":
            ssl_score = 0.85
        elif protocol in ("TLSv1.1", "TLSv1"):
            ssl_score = 0.3

        severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
        for t in threats:
            sev = t.severity if hasattr(t, 'severity') else t.get('severity', 'INFO')
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        total_compliance = len(compliance_issues)
        pass_count = sum(1 for c in compliance_issues
                        if (c.status if hasattr(c, 'status') else c.get('status', '')) == "PASS")

        return {
            "header_coverage": present / total_headers if total_headers > 0 else 0,
            "ssl_strength": ssl_score,
            "threat_count": len(threats),
            "severity_counts": severity_counts,
            "compliance_rate": pass_count / total_compliance if total_compliance > 0 else 0,
            "security_score": security_score.get("score", 0),
            "compliance_score": compliance_score.get("score", 0),
            "has_spf": scan_results.get("dns", {}).get("has_spf", False),
            "has_dmarc": scan_results.get("dns", {}).get("has_dmarc", False),
            "data_exposures": len(content_results.get("data_exposure", [])),
            "mixed_content": len(content_results.get("mixed_content", [])),
            "js_risks": len(content_results.get("javascript_risks", [])),
            "external_resources": len(content_results.get("external_resources", [])),
            "cookie_issues": len(scan_results.get("headers", {}).get("cookie_issues", [])),
        }

    def _detect_anomalies(self, features: dict) -> list[AdaptiveInsight]:
        """Detect anomalies by comparing against learned baselines using z-scores."""
        insights = []
        p = self.profile

        if p.observation_count < 2:
            return insights

        # Check header coverage anomaly
        if p.header_coverage_var > 0:
            z = (features["header_coverage"] - p.header_coverage_mean) / max(math.sqrt(p.header_coverage_var), 0.01)
            if z < -self.ANOMALY_THRESHOLD:
                insights.append(AdaptiveInsight(
                    type="anomaly",
                    title="Unusually Low Header Coverage",
                    description=(
                        f"This site's security header coverage ({features['header_coverage']:.0%}) is "
                        f"significantly below the baseline ({p.header_coverage_mean:.0%}). "
                        f"The adaptive engine has learned that sites with similar gaps tend to have "
                        f"correlated vulnerabilities in transport security and injection protection."
                    ),
                    confidence=min(0.95, 0.5 + abs(z) * 0.15),
                    impact="high" if z < -2.5 else "medium",
                ))
            elif z > self.ANOMALY_THRESHOLD:
                insights.append(AdaptiveInsight(
                    type="anomaly",
                    title="Exceptionally Strong Header Security",
                    description=(
                        f"Header coverage ({features['header_coverage']:.0%}) is well above "
                        f"the learned baseline ({p.header_coverage_mean:.0%}). This suggests "
                        f"mature security practices."
                    ),
                    confidence=min(0.9, 0.4 + abs(z) * 0.1),
                    impact="low",
                ))

        # Check threat count anomaly
        if p.threat_count_var > 0:
            z = (features["threat_count"] - p.threat_count_mean) / max(math.sqrt(p.threat_count_var), 0.5)
            if z > self.ANOMALY_THRESHOLD:
                insights.append(AdaptiveInsight(
                    type="anomaly",
                    title="Elevated Threat Count Detected",
                    description=(
                        f"Detected {features['threat_count']} threats, significantly more than "
                        f"the learned average of {p.threat_count_mean:.1f}. The adaptive model "
                        f"suggests this may indicate systemic security gaps rather than isolated issues."
                    ),
                    confidence=min(0.95, 0.5 + abs(z) * 0.15),
                    impact="high",
                ))

        # SSL strength anomaly
        if p.ssl_strength_var > 0:
            z = (features["ssl_strength"] - p.ssl_strength_mean) / max(math.sqrt(p.ssl_strength_var), 0.01)
            if z < -self.ANOMALY_THRESHOLD:
                insights.append(AdaptiveInsight(
                    type="anomaly",
                    title="Below-Baseline SSL Configuration",
                    description=(
                        f"SSL strength ({features['ssl_strength']:.0%}) is below the learned norm "
                        f"({p.ssl_strength_mean:.0%}). Based on learned patterns, weak SSL often "
                        f"correlates with missing HSTS and incomplete certificate chains."
                    ),
                    confidence=min(0.9, 0.5 + abs(z) * 0.12),
                    impact="high",
                ))

        return insights

    def _analyze_correlations(self, threats: list) -> list[AdaptiveInsight]:
        """Analyze threat category co-occurrences to find correlated vulnerabilities."""
        insights = []
        categories = list(set(
            t.category if hasattr(t, 'category') else t.get('category', '')
            for t in threats
        ))

        if len(categories) < 2:
            return insights

        # Check learned co-occurrence patterns
        strong_correlations = []
        for i, cat1 in enumerate(categories):
            for cat2 in categories[i + 1:]:
                pair_key = f"{min(cat1, cat2)}||{max(cat1, cat2)}"
                count = self.profile.category_cooccurrence.get(pair_key, 0)
                if count >= 3:
                    strong_correlations.append((cat1, cat2, count))

        if strong_correlations:
            top = sorted(strong_correlations, key=lambda x: x[2], reverse=True)[:3]
            pairs_str = ", ".join(f"{c1} + {c2}" for c1, c2, _ in top)
            insights.append(AdaptiveInsight(
                type="learning",
                title="Correlated Vulnerability Clusters Detected",
                description=(
                    f"The self-learning engine has identified recurring threat combinations: "
                    f"{pairs_str}. These categories frequently co-occur, suggesting shared root "
                    f"causes. Addressing the underlying infrastructure issues may resolve "
                    f"multiple threat categories simultaneously."
                ),
                confidence=min(0.95, 0.5 + max(c for _, _, c in top) * 0.05),
                impact="high" if any(c > 5 for _, _, c in top) else "medium",
            ))

        # Detect attack surface breadth
        if len(categories) >= 5:
            insights.append(AdaptiveInsight(
                type="trend",
                title="Broad Attack Surface",
                description=(
                    f"Threats span {len(categories)} different categories, indicating a wide "
                    f"attack surface. The adaptive model has learned that broad exposure "
                    f"requires a prioritized remediation strategy focusing on the highest-impact "
                    f"categories first."
                ),
                confidence=0.8,
                impact="medium",
            ))

        return insights

    def _analyze_compliance_patterns(self, compliance_issues, compliance_score) -> list[AdaptiveInsight]:
        """Analyze compliance patterns and identify regulation-specific weaknesses."""
        insights = []
        breakdown = compliance_score.get("breakdown", {})

        if not breakdown:
            return insights

        # Find worst-performing regulations
        worst = [(reg, score) for reg, score in breakdown.items() if score < 50]
        worst.sort(key=lambda x: x[1])

        if worst:
            reg_list = ", ".join(f"{r} ({s}%)" for r, s in worst[:3])
            insights.append(AdaptiveInsight(
                type="recommendation",
                title="Priority Compliance Gaps Identified",
                description=(
                    f"The adaptive engine identifies critical compliance gaps in: {reg_list}. "
                    f"Based on learned patterns, addressing transport security and data protection "
                    f"headers typically improves scores across multiple regulations simultaneously."
                ),
                confidence=0.85,
                impact="high",
            ))

        # Check for regulation score clustering
        scores = list(breakdown.values())
        if scores:
            mean_score = sum(scores) / len(scores)
            variance = sum((s - mean_score) ** 2 for s in scores) / len(scores)
            if variance < 50:  # Low variance = uniform weakness/strength
                if mean_score < 60:
                    insights.append(AdaptiveInsight(
                        type="learning",
                        title="Uniformly Low Compliance Posture",
                        description=(
                            f"All regulation scores cluster around {mean_score:.0f}% with low "
                            f"variance. This pattern typically indicates fundamental infrastructure "
                            f"gaps (SSL, headers, DNS) rather than regulation-specific issues. "
                            f"The learning model suggests focusing on core security controls."
                        ),
                        confidence=0.78,
                        impact="medium",
                    ))

        return insights

    def _assess_posture(self, features, threats) -> list[AdaptiveInsight]:
        """Assess overall security posture with adaptive context."""
        insights = []

        # Calculate a composite risk indicator
        severity_score = sum(
            features["severity_counts"].get(sev, 0) * weight
            for sev, weight in self.SEVERITY_WEIGHTS.items()
        )

        # Entropy-based diversity check
        total_threats = features["threat_count"]
        if total_threats > 0:
            probs = [
                features["severity_counts"].get(sev, 0) / total_threats
                for sev in self.SEVERITY_WEIGHTS
            ]
            entropy = -sum(p * math.log2(p + 1e-10) for p in probs if p > 0)
            max_entropy = math.log2(len(self.SEVERITY_WEIGHTS))
            normalized_entropy = entropy / max_entropy if max_entropy > 0 else 0

            if normalized_entropy > 0.8:
                insights.append(AdaptiveInsight(
                    type="trend",
                    title="Evenly Distributed Threat Severities",
                    description=(
                        f"Threats are spread across all severity levels (entropy: {normalized_entropy:.2f}). "
                        f"This distribution suggests multiple independent security concerns rather "
                        f"than a single critical vulnerability. The adaptive model recommends "
                        f"a systematic security review."
                    ),
                    confidence=0.72,
                    impact="medium",
                ))
            elif normalized_entropy < 0.3 and features["severity_counts"].get("CRITICAL", 0) > 0:
                insights.append(AdaptiveInsight(
                    type="anomaly",
                    title="Concentrated Critical Threats",
                    description=(
                        f"Threat distribution is heavily concentrated in critical/high severity. "
                        f"This pattern indicates urgent foundational security issues that the "
                        f"learning engine has associated with higher breach probability."
                    ),
                    confidence=0.88,
                    impact="high",
                ))

        # Email security compound risk
        if not features["has_spf"] and not features["has_dmarc"]:
            insights.append(AdaptiveInsight(
                type="recommendation",
                title="Email Security Blind Spot",
                description=(
                    "Both SPF and DMARC are missing, creating a compound phishing risk. "
                    "The adaptive engine has learned that fintech products without email "
                    "authentication are disproportionately targeted by social engineering "
                    "attacks impersonating the brand."
                ),
                confidence=0.82,
                impact="high",
            ))

        return insights

    def _generate_recommendations(self, features, threats, compliance_issues) -> list[AdaptiveInsight]:
        """Generate prioritized recommendations based on learned patterns."""
        insights = []

        # Identify the highest-impact remediation
        if features["header_coverage"] < 0.4 and features["ssl_strength"] < 0.8:
            insights.append(AdaptiveInsight(
                type="recommendation",
                title="Highest-Impact Fix: Security Headers + TLS",
                description=(
                    "The adaptive model has learned that implementing security headers "
                    "(HSTS, CSP, X-Content-Type-Options) combined with TLS 1.2+ provides "
                    "the largest single improvement in both security and compliance scores. "
                    "This addresses the root cause of multiple detected threats."
                ),
                confidence=0.90,
                impact="high",
            ))

        # Check for quick wins
        quick_wins = []
        if features["header_coverage"] < 0.6 and features["header_coverage"] > 0.3:
            quick_wins.append("adding missing security headers")
        if features["cookie_issues"] > 0:
            quick_wins.append("fixing cookie security flags")
        if features["mixed_content"] > 0:
            quick_wins.append("resolving mixed content")

        if quick_wins:
            insights.append(AdaptiveInsight(
                type="recommendation",
                title="Quick Wins Available",
                description=(
                    f"The learning engine identifies these low-effort, high-impact fixes: "
                    f"{', '.join(quick_wins)}. Based on historical patterns, these changes "
                    f"typically improve security scores by 10-20 points."
                ),
                confidence=0.75,
                impact="medium",
            ))

        return insights

    def _update_model(self, features: dict, threats: list):
        """Update the learned model with new observation data (online learning step)."""
        p = self.profile
        alpha = self.LEARNING_RATE

        # Update count
        p.observation_count += 1

        # EMA update for continuous features
        p.header_coverage_mean = (1 - alpha) * p.header_coverage_mean + alpha * features["header_coverage"]
        p.header_coverage_var = (1 - alpha) * p.header_coverage_var + alpha * (features["header_coverage"] - p.header_coverage_mean) ** 2

        p.threat_count_mean = (1 - alpha) * p.threat_count_mean + alpha * features["threat_count"]
        p.threat_count_var = (1 - alpha) * p.threat_count_var + alpha * (features["threat_count"] - p.threat_count_mean) ** 2

        p.ssl_strength_mean = (1 - alpha) * p.ssl_strength_mean + alpha * features["ssl_strength"]
        p.ssl_strength_var = (1 - alpha) * p.ssl_strength_var + alpha * (features["ssl_strength"] - p.ssl_strength_mean) ** 2

        p.compliance_rate_mean = (1 - alpha) * p.compliance_rate_mean + alpha * features["compliance_rate"]
        p.compliance_rate_var = (1 - alpha) * p.compliance_rate_var + alpha * (features["compliance_rate"] - p.compliance_rate_mean) ** 2

        # Update severity distribution
        total = features["threat_count"] or 1
        for sev in p.severity_distribution:
            observed = features["severity_counts"].get(sev, 0) / total
            p.severity_distribution[sev] = (1 - alpha) * p.severity_distribution[sev] + alpha * observed

        # Update co-occurrence matrix
        categories = list(set(
            t.category if hasattr(t, 'category') else t.get('category', '')
            for t in threats
        ))
        for i, cat1 in enumerate(categories):
            for cat2 in categories[i + 1:]:
                pair_key = f"{min(cat1, cat2)}||{max(cat1, cat2)}"
                current = p.category_cooccurrence.get(pair_key, 0)
                p.category_cooccurrence[pair_key] = current * self.DECAY_FACTOR + 1

        p.last_updated = datetime.now(timezone.utc).isoformat()

        # Persist the updated model
        self._save_profile()

    def _load_profile(self) -> SecurityProfile:
        """Load the learned security profile from disk."""
        try:
            if os.path.exists(self.profile_path):
                with open(self.profile_path, "r") as f:
                    data = json.load(f)
                return SecurityProfile(**data)
        except (json.JSONDecodeError, TypeError, KeyError):
            pass
        return SecurityProfile()

    def _save_profile(self):
        """Persist the learned profile to disk."""
        try:
            os.makedirs(os.path.dirname(self.profile_path), exist_ok=True)
            with open(self.profile_path, "w") as f:
                json.dump(asdict(self.profile), f, indent=2, default=str)
        except (OSError, IOError):
            pass  # Non-critical - learning state is ephemeral in serverless

    @staticmethod
    def _default_profile_path() -> str:
        """Default path for the learned profile."""
        return os.path.join(
            os.environ.get("TMPDIR", "/tmp"),
            "fintech_threat_agent",
            "adaptive_profile.json",
        )

    @staticmethod
    def _score_to_rating(score: int) -> str:
        """Convert a numeric score to a rating label."""
        if score >= 90:
            return "Excellent"
        if score >= 75:
            return "Good"
        if score >= 60:
            return "Fair"
        if score >= 40:
            return "Poor"
        return "Critical"
